name: Scrape Filmarks and Upload to Lolipop

on:
    push:
      branches:
        - main
    schedule:
      - cron: '0 3 * * *'  # 毎日03:00に実行
    workflow_dispatch:  # 手動実行も可能

jobs:
  scrape_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: デバッグ -> 現在のディレクトリ構成を確認
        run: |
          echo "✅ [INFO] Current Working Directory:"
          pwd
          echo "✅ [INFO] Home Directory Structure:"
          ls -al ~/
          echo "✅ [INFO] Root Directory Structure:"
          ls -al /
          echo "✅ [INFO] Project Root Directory Structure:"
          ls -al $GITHUB_WORKSPACE
          echo "✅ [INFO] Checking data/ directory:"
          ls -al $GITHUB_WORKSPACE/data || echo "❌ [ERROR] data/ directory does not exist!"

      - name: Python 環境をセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 依存関係をインストール
        run: pip install -r app/requirements.txt

      - name: SQLiteデータ保存用のディレクトリを作成
        run: mkdir -p $GITHUB_WORKSPACE/data

      - name: スクレイピングを実行
        run: python app/scraper.py

      - name: デバッグ -> reviews.db の存在を確認
        run: |
          echo "✅ [INFO] Checking reviews.db existence:"
          if [ -f "$GITHUB_WORKSPACE/data/reviews.db" ]; then
            echo "✅ [INFO] reviews.db found!"
          else
            echo "❌ [ERROR] reviews.db not found!"
            exit 1
          fi

      - name: レンタルサーバーに `reviews.db` をアップロード
        env:
          LOLI_SFTP_HOST: ${{ secrets.LOLI_SFTP_HOST }}
          LOLI_SFTP_USER: ${{ secrets.LOLI_SFTP_USER }}
          LOLI_SFTP_PASSWORD: ${{ secrets.LOLI_SFTP_PASSWORD }}
        run: |
          sudo apt-get install -y lftp
          lftp -d -e "
          set sftp:auto-confirm yes;
          open -p 2222 -u $LOLI_SFTP_USER,$LOLI_SFTP_PASSWORD sftp://$LOLI_SFTP_HOST;
          cd web/data;
          put $GITHUB_WORKSPACE/data/reviews.db reviews.db;
          bye"