name: Scrape Filmarks and Upload to Lolipop

on:
    push:
      branches:
        - main
    schedule:
      - cron: '0 3 * * *'  # 毎日03:00に実行
    workflow_dispatch:  # 手動実行も可能

jobs:
  scrape_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: デバッグ -> 作業ディレクトリの確認
        run: |
          echo "現在のカレントディレクトリ:"
          pwd
          echo "ルートディレクトリの内容:"
          ls -al
          echo "dataディレクトリの内容（あれば表示）:"
          ls -al data/ || echo "dataディレクトリが存在しません"

      - name: Python 環境をセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 依存関係をインストール
        run: pip install -r app/requirements.txt

      - name: SQLiteデータ保存用のディレクトリを作成
        run: mkdir -p data

      - name: スクレイピングを実行
        run: python app/scraper.py

      - name: デバッグ -> reviews.db の存在を確認
        run: |
          echo "現在のカレントディレクトリ:"
          pwd
          echo "dataディレクトリの内容:"
          ls -al data/ || echo "dataディレクトリが存在しません"
          echo "reviews.db の存在チェック:"
          if [ -f "data/reviews.db" ]; then
            echo "reviews.db が正しく作成されています。"
          else
            echo "エラー: reviews.db が見つかりません。"
            exit 1
          fi

      - name: レンタルサーバーに `reviews.db` をアップロード
        env:
          LOLI_SFTP_HOST: ${{ secrets.LOLI_SFTP_HOST }}
          LOLI_SFTP_USER: ${{ secrets.LOLI_SFTP_USER }}
          LOLI_SFTP_PASSWORD: ${{ secrets.LOLI_SFTP_PASSWORD }}
        run: |
          sudo apt-get install -y lftp
          lftp -d -e "
          set sftp:auto-confirm yes;
          open -p 2222 -u $LOLI_SFTP_USER,$LOLI_SFTP_PASSWORD sftp://$LOLI_SFTP_HOST;
          cd web/data;
          put ./data/reviews.db reviews.db;
          bye"