name: Scrape Filmarks and Upload to Lolipop

on:
    push:
      branches:
        - main
    schedule:
      - cron: '0 3 * * *'  # 毎日03:00に実行
    workflow_dispatch:  # 手動実行も可能

jobs:
  scrape_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Python 環境をセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 依存関係をインストール
        run: pip install -r app/requirements.txt

      - name: スクレイピングを実行
        run: python app/scraper.py

      - name: SQLiteデータ保存用のディレクトリを作成
        run: mkdir -p app/data

      - name: レンタルサーバーに `reviews.db` をアップロード
        env:
          LOLI_SFTP_HOST: ${{ secrets.LOLI_SFTP_HOST }}
          LOLI_SFTP_USER: ${{ secrets.LOLI_SFTP_USER }}
          LOLI_SFTP_PASSWORD: ${{ secrets.LOLI_SFTP_PASSWORD }}
        run: |
          sudo apt-get install -y lftp
          lftp -e "set sftp:auto-confirm yes; open -u $LOLI_SFTP_USER,$LOLI_SFTP_PASSWORD sftp://$LOLI_SFTP_HOST; put -O /path/to/htdocs/data/ app/data/reviews.db; bye"

env:
  LOLI_SFTP_HOST: ${{ secrets.LOLI_SFTP_HOST }}
  LOLI_SFTP_USER: ${{ secrets.LOLI_SFTP_USER }}
  LOLI_SFTP_PASSWORD: ${{ secrets.LOLI_SFTP_PASSWORD }}